export enum EVideoAction {
    SET_VIDEO_PARAMS = 'pattern/video/set-video-param',
    SET_EDGE_MODE = 'pattern/video/set-edge-mode',
    SET_MIRROR_MODE = 'pattern/video/set-mirror-mode',
    SET_SLIT_MODE = 'pattern/video/set-slit-mode',
    SET_DEVICE = 'pattern/video/set-device',
    SET_STACK_TYPE = 'pattern/video/set-stack-type',
    SET_CHANGE_FUNCTION = 'pattern/video/set-change-function',
    SET_STACK_SIZE = 'pattern/video/set-stack-size',
    SET_CUT_OFFSET = 'pattern/video/set-cut-offset',
    START_CAMERA = 'pattern/video/start-camera',
    STOP_CAMERA = 'pattern/video/stop-camera',
    START_UPDATING = 'pattern/video/start-updating',
    STOP_UPDATING = 'pattern/video/stop-updating',
}
